"""Fail-closed static verifier for the source-only Hunyuan road junction kit."""

import argparse
import ast
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SCRIPT = Path(__file__).with_name("build-hf-road-junctions.py")
OUTPUT_ROOT = (
    ROOT / "modules" / "space_exploration" / "assets" / "source" / "blender"
    / "world-kits" / "mf-road-junctions-v1"
)
DEFAULT_REPORT = OUTPUT_ROOT / "mf-road-junctions-v1.provenance.json"
STRAIGHT = (
    OUTPUT_ROOT.parent / "mf-road-straight-hunyuan-clean-v1" / "review-exports"
    / "mf-road-straight-hunyuan-clean-v1-lod0-review.glb"
)
STRAIGHT_SHA = "69D406836DB64BAF6154761332E04260DA8EF0A95C29FB006317834178EDC2F9"
EXPECTED_CONNECTIONS = {
    "corner_90": {"S": 20.0, "E": 20.0},
    "t_junction": {"S": 20.0, "E": 20.0, "W": 20.0},
    "x_plaza": {"N": 20.0, "E": 20.0, "S": 20.0, "W": 20.0},
    "straight_endcap": {"S": 20.0},
    "primary_local_adapter": {"S": 20.0, "N": 12.0},
}
EXPECTED_POSITIONS = {"N": [0.0, 20.0], "E": [20.0, 0.0], "S": [0.0, -20.0], "W": [-20.0, 0.0]}
EXPECTED_VIEWS = {"top", "iso", "edge", "seam_top", "seam_iso"}


def digest(path):
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest().upper()


def checked_file(record, label):
    path = Path(record.get("path", ""))
    if not path.is_file():
        raise SystemExit("FAIL missing %s: %s" % (label, path))
    actual = digest(path)
    if actual != str(record.get("sha256", "")).upper():
        raise SystemExit("FAIL stale %s hash: %s" % (label, path))
    if path.stat().st_size != record.get("bytes"):
        raise SystemExit("FAIL stale %s byte count: %s" % (label, path))
    return path


def png_dimensions(path):
    header = path.read_bytes()[:24]
    if len(header) != 24 or header[:8] != b"\x89PNG\r\n\x1a\n" or header[12:16] != b"IHDR":
        raise SystemExit("FAIL invalid evidence PNG: " + str(path))
    return int.from_bytes(header[16:20], "big"), int.from_bytes(header[20:24], "big")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    args = parser.parse_args()
    ast.parse(SCRIPT.read_text(encoding="utf-8"))
    if digest(STRAIGHT) != STRAIGHT_SHA:
        raise SystemExit("FAIL immutable cleaned-straight hash mismatch")
    report = json.loads(args.report.read_text(encoding="utf-8"))
    if report.get("schema") != "MassfrontHunyuanRoadJunctionsV1":
        raise SystemExit("FAIL junction schema mismatch")
    if report.get("status") != "SOURCE_AUTHORING_ONLY":
        raise SystemExit("FAIL junction status is not source-authoring-only")
    if report.get("runtimeAccepted") is not False or report.get("visualAccepted") is not False:
        raise SystemExit("FAIL source candidate was promoted without visual/runtime acceptance")
    # Older source-only reports predate generatorScript recording; syntax is
    # still required and all immutable inputs/derived outputs remain hashed.
    # Future builder runs include the generator record and it is verified when
    # present without retroactively rewriting an earlier provenance report.
    generator = report.get("generatorScript")
    if generator:
        checked_file(generator, "generator script")
        if str(generator.get("sha256", "")).upper() != digest(SCRIPT):
            raise SystemExit("FAIL provenance was generated by another script revision")
    if str(report.get("straightSource", {}).get("sha256", "")).upper() != STRAIGHT_SHA:
        raise SystemExit("FAIL junction provenance references a different straight source")
    contract = report.get("contract", {})
    if contract.get("gridM") != 40.0 or contract.get("primaryWidthM") != 20.0 or contract.get("localWidthM") != 12.0:
        raise SystemExit("FAIL road-grid width contract mismatch")

    pieces = report.get("pieces", [])
    by_id = {item.get("id"): item for item in pieces}
    if set(by_id) != set(EXPECTED_CONNECTIONS) or len(pieces) != len(EXPECTED_CONNECTIONS):
        raise SystemExit("FAIL missing or duplicate junction pieces")
    triangle_inventory = {}
    for piece_id, expected in EXPECTED_CONNECTIONS.items():
        piece = by_id[piece_id]
        sockets = piece.get("sockets", [])
        by_direction = {item.get("direction"): item for item in sockets}
        if set(by_direction) != set(expected) or len(sockets) != len(expected):
            raise SystemExit("FAIL socket directions for " + piece_id)
        for direction, width in expected.items():
            socket = by_direction[direction]
            if socket.get("widthM") != width:
                raise SystemExit("FAIL socket width for %s/%s" % (piece_id, direction))
            position = socket.get("position", [])
            if len(position) < 2 or position[:2] != EXPECTED_POSITIONS[direction]:
                raise SystemExit("FAIL socket position for %s/%s" % (piece_id, direction))
        lods = piece.get("lods", [])
        triangles = [item.get("triangles") for item in lods]
        if len(triangles) != 3 or not all(isinstance(value, int) and value > 0 for value in triangles):
            raise SystemExit("FAIL LOD inventory for " + piece_id)
        if not triangles[0] > triangles[1] > triangles[2]:
            raise SystemExit("FAIL LOD counts are not descending for " + piece_id)
        if any(item.get("intersectionAccounting", {}).get("unexpectedIntersections") != 0 for item in lods):
            raise SystemExit("FAIL rendered geometry intersections for " + piece_id)
        if piece.get("collisionTriangles", 0) <= 0 or piece.get("navTriangles", 0) <= 0:
            raise SystemExit("FAIL collision/nav inventory for " + piece_id)
        triangle_inventory[piece_id] = triangles

    exports = report.get("exports", {})
    if set(exports) != set(EXPECTED_CONNECTIONS):
        raise SystemExit("FAIL export inventory mismatch")
    for piece_id, group in exports.items():
        lods = group.get("lods", [])
        if len(lods) != 3:
            raise SystemExit("FAIL exported LOD count for " + piece_id)
        for record in lods:
            checked_file(record, piece_id + " LOD export")
        checked_file(group.get("collision", {}), piece_id + " collision export")
        checked_file(group.get("nav", {}), piece_id + " nav export")

    renders = report.get("evidence", {}).get("renders", [])
    if len(renders) != 25:
        raise SystemExit("FAIL expected 25 matched evidence renders")
    seen = {piece_id: set() for piece_id in EXPECTED_CONNECTIONS}
    for record in renders:
        piece_id, view = record.get("piece"), record.get("view")
        if piece_id not in seen or view not in EXPECTED_VIEWS or view in seen[piece_id]:
            raise SystemExit("FAIL evidence identity/duplicate: %s/%s" % (piece_id, view))
        path = checked_file(record, "evidence render")
        if png_dimensions(path) != (1024, 1024):
            raise SystemExit("FAIL evidence render dimensions: " + str(path))
        seen[piece_id].add(view)
    if any(views != EXPECTED_VIEWS for views in seen.values()):
        raise SystemExit("FAIL incomplete matched view set")
    checked_file(report.get("blend", {}), "authoring blend")
    limitations = " ".join(report.get("knownLimitations", [])).lower()
    if "not runtime registered" not in limitations or "pbr" not in limitations:
        raise SystemExit("FAIL material/runtime limitations are not disclosed")
    print(json.dumps({
        "status": "PASS", "runtimeAccepted": False, "visualAccepted": False,
        "pieces": sorted(by_id), "lodTriangles": triangle_inventory,
        "evidenceRenders": len(renders), "straightSha256": STRAIGHT_SHA,
    }, separators=(",", ":")))


if __name__ == "__main__":
    main()
