/* Turn a Blender export into geometry the game can instance.

   The export from tools/blender_export.py arrives as parallel arrays with
   MATERIAL NAMES and a bone index per vertex. This resolves those names against
   the real MAT table in src/engine/materials.js — so the atlas can be
   re-ordered without invalidating a single authored model — packs material and
   bone into the one float the vertex format carries, and writes the exact
   12-float layout MeshBuilder produces.

   The output is a small JS module assigning into MF_BLENDER_GEO, which
   src/engine/models.js consumes. Deliberately JS and not a binary blob: this
   codebase loads classic scripts from a manifest and has no asset-fetch path
   for geometry, so a .js file needs no new loader, no new failure mode, and no
   change to the OTA payload format.

   Usage:
     node tools/blender_import.mjs <export.json> [--out assets/data/meshes.js]
*/
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const inFile = args.find(a => !a.startsWith('--'));
if (!inFile) { console.error('usage: node tools/blender_import.mjs <export.json> [--out <file>]'); process.exit(1); }
const outIdx = args.indexOf('--out');
const outFile = outIdx >= 0 ? args[outIdx + 1] : 'assets/data/meshes.js';

/* Read the REAL material ids rather than duplicating them. A second copy here
   would drift the first time the atlas gains a tile, and the failure would be
   every Blender model silently rendering with the wrong surface. */
const matSrc = readFileSync(join(root, 'src/engine/materials.js'), 'utf8');
const matBlock = matSrc.slice(matSrc.indexOf('const MAT={'));
const MAT = {};
for (const m of matBlock.slice(0, matBlock.indexOf('}')).matchAll(/([A-Z_]+)\s*:\s*(\d+)/g))
  MAT[m[1]] = +m[2];
if (!Object.keys(MAT).length) { console.error('could not read MAT from src/engine/materials.js'); process.exit(1); }

const ex = JSON.parse(readFileSync(inFile, 'utf8'));
if (!ex.ok) { console.error('export failed: ' + (ex.error || 'unknown')); process.exit(1); }
(ex.warnings || []).forEach(w => console.warn('  warning: ' + w));

const n = ex.mat.length;
/* Stride comes from the engine, not from a literal: the one time this was a
   hand-written 12, growing the vertex silently corrupted every import. */
const meshSrc = readFileSync(join(root, 'src/engine/mesh.js'), 'utf8');
const VF = +(meshSrc.match(/VFLOATS\s*=\s*(\d+)/) || [0, 12])[1];
const V = new Float32Array(n * VF);
const missing = new Set();
for (let k = 0; k < n; k++) {
  const name = ex.mat[k];
  let id = MAT[name];
  if (id === undefined) { missing.add(name); id = MAT.PLATE ?? 0; }
  const bone = ex.bone[k] | 0;
  /* Same packing MeshBuilder._mid uses: integer part is material+1, fraction is
     bone+1 over 128, sign carries team livery. Exactly lossless for material
     ids under 64 and bone indices under 128. */
  const mid = ((id + 1) + (bone + 1) / 128) * (ex.team[k] ? -1 : 1);
  const o = k * VF;
  V[o] = ex.p[k * 3]; V[o + 1] = ex.p[k * 3 + 1]; V[o + 2] = ex.p[k * 3 + 2];
  V[o + 3] = ex.n[k * 3]; V[o + 4] = ex.n[k * 3 + 1]; V[o + 5] = ex.n[k * 3 + 2];
  V[o + 6] = ex.c[k * 3]; V[o + 7] = ex.c[k * 3 + 1]; V[o + 8] = ex.c[k * 3 + 2];
  V[o + 9] = ex.uv[k * 2]; V[o + 10] = ex.uv[k * 2 + 1];
  V[o + VF - 1] = mid;
}
if (missing.size) console.warn('  warning: unknown materials -> PLATE: ' + [...missing].join(', '));

const I = new Uint16Array(ex.i);
const f = a => '[' + Array.from(a).map(x => +x.toFixed(4)).join(',') + ']';
const body = `/* GENERATED by tools/blender_import.mjs — do not hand-edit.
   Source: ${ex.name}  ${ex.tris} triangles, ${ex.verts} vertices.
   Vertex layout matches MeshBuilder exactly: pos(3) nrm(3) col(3) uv(2) mat+bone(1). */
MF_BLENDER_GEO[${JSON.stringify(ex.name)}]={v:new Float32Array(${f(V)}),i:new Uint16Array(${f(I)}),count:${I.length}};
`;
mkdirSync(dirname(join(root, outFile)), { recursive: true });
writeFileSync(join(root, outFile), body, 'utf8');
console.log(`${ex.name}: ${ex.tris} tris, ${ex.verts} verts -> ${outFile} (${(body.length / 1024).toFixed(0)} KB)`);
