#!/usr/bin/env python3
"""Inline the generated item art as data URIs.

Run after tools/make-icons.py. The map is emitted as an ordinary source file so
that one code path serves every target — the folder build, the single-file
bundle and a patch downloaded by the updater. A linked path would work in two of
those three and quietly fall back to an emoji in the other.
"""
import base64, glob, os, json
root = os.path.join(os.path.dirname(__file__), '..')
out = []
for f in sorted(glob.glob(os.path.join(root, 'assets/icons/items/*.png'))):
    k = os.path.splitext(os.path.basename(f))[0]
    b = base64.b64encode(open(f, 'rb').read()).decode()
    out.append(' %s:"data:image/png;base64,%s"' % (json.dumps(k), b))
src = ('/* Generated by tools/embed-icons.py — do not edit. */\n'
       'const ITEM_ART={\n' + ',\n'.join(out) + '\n};\n')
open(os.path.join(root, 'assets/data/itemart.js'), 'w').write(src)
print('wrote %d icons -> assets/data/itemart.js' % len(out))
